# Site settings
title: Muhammed Rasheed
description: Official GitHub page of Muhammed Rasheed
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://rasheedk.github.io

# User settings
username: rasheedk
user_description: A passionate java developer who focuses on mobile software development including Andoid , iOS and UI designs.
user_title: Senior Android Software Engineer
email: rasheedbengaluru@gmail.com
twitter_username: Muhamme50842804
github_username:  rasheedk
gplus_username:  rasheedbengaluru

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
